//1 FAIRE METHODE POUR CHERHCER UNE STRING ET LA COMPARER AVRC UNE AUTRE
//2 FAIRE UNE METHODE POUR VERIFIER LES DATES DEMPRUNT

//3 VERIFIER SI UN LIVRE QUON SOUHAITE RAJOUTE AU STOCK EXISTE
// ET SIL EXISTE AUGMENTE LE NOMBRE DEXEMPLAIRE POUR EVITE LES DOUBLONS
// DE MEME POUR LES CLIENTS POUR EVITER LES DOUBLONS



#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "index.h"


